# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

baseURL: https://aanghelidi.gitlab.io/blog/
defaultContentLanguage: en
theme: blowfish

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

buildDrafts: false
buildFuture: false
enableRobotsTXT: true
paginate: 10
summaryLength: 0

# googleAnalytics = "G-XXXXXXXXX"

imaging:
  anchor: Center
outputs:
  home:
  - HTML
  - RSS
  - JSON
related:
  indices:
  - name: tags
    weight: 100
  - name: categories
    weight: 100
  - name: series
    weight: 50
  - name: authors
    weight: 20
  - name: date
    weight: 10
  - applyFilter: false
    name: fragmentrefs
    type: fragments
    weight: 10
  threshold: 0
  toLower: false
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
