baseurl: https://aanghelidi.gitlab.io
title: Alain Anghelidi
languageCode: en-us
params:
  author: Alain Anghelidi
  description: Alain Anghelidi is a Machine Learning Engineer. He is passionate about bringing the gap between the machine learning experimentation and usage in production by applying engineering best practices.
menu:
  main:
    - name: Posts
      url: /blog/posts/
    - name: Projects
      url: /blog/projects/
  social:
    - name: Github
      url: https://github.com/aanghelidi
    - name: Gitlab
      url: https://gitlab.com/aanghelidi
  footer:
    - name: Github
      url: https://github.com/aanghelidi
    - name: Gitlab
      url: https://gitlab.com/aanghelidi
    - name: LinkedIn
      url: https://www.linkedin.com/in/alain-anghelidi/
    - name: Twitter
      url: https://twitter.com/alangel12407606
