baseurl: https://aanghelidi.gitlab.io/blog/
theme: hugo-bearblog
title: Alain Anghelidi
author: Alain Anghelidi
languageCode: en-us
copyright: "Copyright \xA9 2023, Alain Anghelidi."
disableKinds:
- taxonomy
ignoreErrors:
- error-disable-taxonomy
permalinks:
  blog: /:slug/
  tags: /blog/:slug
params:
  description: 'Alain Anghelidi blog'
  favicon: images/favicon.png
  images:
  - images/share.png
  title: "Alain Anghelidi"



    #menu:
    #  main:
    #    - name: Posts
    #      url: /blog/posts/
    #    - name: Projects
    #      url: /blog/projects/
    #  social:
    #    - name: Github
    #      url: https://github.com/aanghelidi
    #    - name: Gitlab
    #      url: https://gitlab.com/aanghelidi
    #  footer:
    #    - name: Github
    #      url: https://github.com/aanghelidi
    #    - name: Gitlab
    #      url: https://gitlab.com/aanghelidi
    #    - name: LinkedIn
    #      url: https://www.linkedin.com/in/alain-anghelidi/
    #    - name: Twitter
    #      url: https://twitter.com/alangel12407606
    #







