baseurl: http://localhost:1313
theme: hugo-bearblog
title: Alain Anghelidi
author: Alain Anghelidi
languageCode: en-us
copyright: "Copyright \xA9 2023, Alain Anghelidi."
disableKinds:
- taxonomy
ignoreErrors:
- error-disable-taxonomy
permalinks:
  blog: /:slug/
  tags: /blog/:slug
params:
  description: 'Alain Anghelidi blog'
  favicon: images/favicon.png
  images:
  - images/share.png
  title: "Alain Anghelidi"

