baseurl: https://aanghelidi.gitlab.io/blog/
title: aanghelidi
theme: console
languageCode: en-us
params:
  titleCutting: true
  custom_css:
    - css/console.css
    - css/lineicons.css
  navlinks:
    - name: RSS
      url: index.xml
    - name: about/
      url: about/
    - name: posts/
      url: posts/
    - name: projects/
      url: projects/
  socialinks:
    - name: Github
      url: https://github.com/aanghelidi
    - name: Gitlab
      url: https://gitlab.com/aanghelidi
    - name: LinkedIn
      url: https://www.linkedin.com/in/alain-anghelidi/
    - name: Twitter
      url: https://twitter.com/alangel12407606
